
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeeshop
  template:
    metadata:
      labels:
        app: coffeeshop
    spec:
      containers:
      - name: coffeeshop-app
        image: coffeeshop-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffeeshop-service
spec:
  type: NodePort
  selector:
    app: coffeeshop
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
